# Generated by Django 5.0.4 on 2024-05-03 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='votes',
        ),
        migrations.AddField(
            model_name='message',
            name='voters',
            field=models.ManyToManyField(related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!d7FrDKN9LCw6Wbb0WOPsjjwg9bZp8bYuHMo1mvEP', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('question', True)), fields=('question',), name='question_message'),
        ),
    ]
