# Generated by Django 5.0.4 on 2024-04-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!dom9n9E7dA7xf3mvG3fQ1PTbsTJlRVyHQyGyMx46', max_length=128),
        ),
    ]
