# Generated by Django 5.0.4 on 2024-04-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!1nd97F7qilu8w1ydLgDERN7g5kpcenPLjRWx3eEc', max_length=128),
        ),
    ]
