# Generated by Django 5.0.4 on 2024-04-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0002_user_is_staff_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!lx5vO68jlNAHL3po9y14h8UQtWvLY7SkjFCPb8wy', max_length=128),
        ),
    ]
