# Generated by Django 5.0.4 on 2024-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!LKrnLu1zdqlgAkZWRqkdCQGPqqV71iMbs7Jft9ol', max_length=128),
        ),
    ]
