# Generated by Django 5.0.4 on 2024-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0002_remove_message_votes_message_voters_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='question_message',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!bgeHl0RS9F4dDI6wda2aw9RCIfUT3MDrX7M9PiT7', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('question', True)), fields=('thread', 'question'), name='question_message'),
        ),
    ]
