# Generated by Django 5.0.4 on 2024-05-04 22:03

import asapp.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0003_remove_message_question_message_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default='', null=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(asapp.models.User.dead), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!BjmTd18L0c9T3j8t9nCv8Te8SshfLTKEpMjnfrF0', max_length=128),
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.ManyToManyField(related_name='reports', to='asapp.reporttag'),
        ),
    ]
