# Generated by Django 5.0.4 on 2024-05-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!7VRfi3qDYY6eqhor0La6yvERlHSdLsC5vsKqLptT', max_length=128),
        ),
    ]
