# Generated by Django 5.0.4 on 2024-04-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!Y57ct71q1ZfxhKbitc9Q15sMjTUyPXGPzywJepYZ', max_length=128),
        ),
    ]
