# Generated by Django 5.0.4 on 2024-04-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!v5bNJdVYAQJlTyc9PNwoTgAQnEyWcQANLfA5VXwZ', max_length=128),
        ),
    ]
