# Generated by Django 5.0.4 on 2024-05-01 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0004_remove_thread_date_message_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!lnLcklf5tbVUNzBEcpyOu46TPZYd80dnT3uE4QSn', max_length=128),
        ),
    ]
