# Generated by Django 5.0.4 on 2024-05-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!34LD2yiefNSanpf6HwzHQYCqJL54qvxoiqKqpro9', max_length=128),
        ),
    ]
