# Generated by Django 5.0.4 on 2024-05-04 22:48

import asapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(default=2, on_delete=models.SET(asapp.models.Message.dead), related_name='reported_msgs', to='asapp.message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!yN8qp8ldCroEIKYpVZ0Ey6FHQyjkC7lhWhljhzt4', max_length=128),
        ),
    ]
