# Generated by Django 5.0.4 on 2024-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='userTagSubscriptions', to='asapp.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!bH6P1JH5l4Aguunx9i9JPQOXIs0BI9vXCj9k3Dyt', max_length=128),
        ),
    ]
