# Generated by Django 5.0.4 on 2024-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0007_report_message_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!pcPeG8Pi8PLvEngx1lq3pOUAZwmo39GDEGsqTByt', max_length=128),
        ),
    ]
