# Generated by Django 5.0.4 on 2024-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asapp', '0007_user_tags_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!Sa532eK2b5ecQJEEB9cW4ffGzKJQMckhj1dcVZpE', max_length=128),
        ),
    ]
