# Generated by Django 5.0.2 on 2024-02-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
